export const CONFIG_APP_PORT = '8080'
export const STATUS_SUCCESS = 'SUCCESS'
export const STATUS_FAILURE = 'FAILURE'
export const BAD_REQUEST = 'BAD_REQUEST'
export const STATUS_DUPLICATE = 'DUPLICATE'
export const VALIDATION_ERRORS = 'VALIDATION_ERRORS'
export const API_ERROR = 'API_ERROR'
export const EC_TECHNICAL_ERROR = 'TECHNICAL_ERROR'

export const API_ERROR_RESPONSE = {
  status: STATUS_FAILURE,
  errorCode: API_ERROR
}
